# Generated by Django 3.0.5 on 2021-12-06 10:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenNft',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('name', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200)),
                ('token_id', models.IntegerField(default=0)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=42)),
                ('private_key', models.CharField(max_length=56)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
